### ISSUE TITLE
This script can't support  Ida 7.0 ?

### ISSUE THREAD

**Issue by CaiJiJi** [tintinweb/ida-batch_decompile#3]
Ida > 7.0 dont have **idaapi.add_menu_item** . sad:( 
![photo6194737314090035237](https://user-images.githubusercontent.com/10561685/42364976-a4e0b926-812f-11e8-8f1b-291c6c4bb399.jpg)

**Comment by tintinweb** [comment]
@CaiJiJi, let's make it work with >=7.0 then 👍 

according to [this bug on x64dbg](https://github.com/x64dbg/x64dbgida/issues/4) with 7.0 we're supposed to use a different api. Unfortunately the free 7.0 version does not appear to have idapython support therefore I cannot test it :/

**Comment by tintinweb** [comment]
please give it a try. as mentioned, I do not have an idaapi enabled 7.0 version available and blindly tried to implement the new actionapi see https://github.com/tintinweb/ida-batch_decompile/tree/fix/support_70

sidenote: the cmdline decompiler may still work. give it a try.

**Comment by CaiJiJi** [comment]
Still can't run here, there is IDA7.0 Crack, can　you  try it？　thanks
(--redacted--)

**Comment by tintinweb** [comment]
not going to run software from untrusted sources or support spreading unofficial versions. can you provide the error message? maybe we can figure this out

**Comment by tintinweb** [comment]
a user was so kind and privided me with details on how to fix this. see https://github.com/tintinweb/ida-batch_decompile/pull/4. should be fine now.
closing this issue. please add any comments to the PR #4
