### ISSUE TITLE
Erm is it python don't work in Ida 7.0?

### ISSUE THREAD

**Issue by ericsia** [tintinweb/ida-batch_decompile#6]
I notice my script format don't have .py filter, so I switch to All Files(*.*)
D:\ida_batch_decompile.py: D:\ida_batch_decompile.py,1: Bad or ill-formed preprocessor command

**Comment by tintinweb** [comment]
follow this: https://github.com/tintinweb/ida-batch_decompile#idascript-gui-mode

yes, it should work for ida 7.0
