### ISSUE TITLE
"SyntaxError: invalid syntax" and "NameError: name 'Choose2' is not defined"

### ISSUE THREAD

**Issue by TBirdSoars** [tintinweb/ida-batch_decompile#8]
I cloned the repository to use the latest script, and tried using the "idascript (gui mode)" method on IDA Pro 7.5. I received the following error:

```
File "C:\IDA 7.5\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/repos/ida-batch_decompile/ida_batch_decompile.py", line 57
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

I corrected the ```except Exception, e:``` error and similar errors like in https://github.com/tintinweb/ida-batch_decompile/commit/d7dd5942278470bbd0c147fdb697a09d23998091 , but this lead to another error:

```
File "C:\IDA 7.5\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/repos/ida-batch_decompile/ida_batch_decompile.py", line 176
    print "[+] stats: %r" % stats
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[+] stats: %r" % stats)?
```

I added the parentheses to all effected ```print``` statements, but then:

```
File "C:\IDA 7.5\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "C:/repos/ida-batch_decompile/ida_batch_decompile.py", line 423, in <module>
    class TestEmbeddedChooserClass(Choose,Choose2):
NameError: name 'Choose2' is not defined
```

At that point, I'm not sure how to fix this. Any help would be appreciated.

Edit:
I've since made a fork that might be exclusive to IDA 7.4+:
https://github.com/TBirdSoars/ida-batch_decompile

IDA no longer throws errors when loading the script through
```File -> Script file... -> ida_batch_decompile.py```
and ```IDA Batch Decompile``` appears under ```File -> Produce file```.

Unfortunately, selecting this appears to do nothing, and I'm not sure why.

**Comment by mrmarten** [comment]
Same happend for me! Maybe its not supporting Python3?

**Comment by tintinweb** [comment]
Oh yeah, it's for python2 (this repo is 5yrs old ;)) 

@mrmarten @TBirdSoars 

I think I also use the script with https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-decompiler
